kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-kube-system-consul-server-0
  namespace: kube-system
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
